'''
Exception Handeling
'''

a = 5/0 

print('After Error')

